### ISSUE TITLE
cargo-vibe

### ISSUE THREAD

**Issue by Shadlock0133** [vmfunc/cargo-buttplug#1]
hi, hey, i already made this https://github.com/Shadlock0133/cargo-vibe, my lawyers are gonna contact you in 3-8 business days /s

but actually, hey, nice to see someone else have the same idea 😸

~Aurora

**Comment by vmfunc** [comment]
oh wow, i'm so sorry we didn't know an actual repo already existed 😭 

glad to see someone else did have that idea too x-x
